version: "3"

services:
  backend:
    build: ./backend
    command: python app.py
    ports:
      - "8087:8087"

  frontend:
    build: ./frontend
    command: nodemon server.js
    ports:
      - "8088:8088"
    environment:
      APP_URL: http://backend:8087
    depends_on:
      - backend
